name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
            config:
              - os: ubuntu-latest
                generator: Ninja
                cmake_args: ""
                artifact: nba-libretro_linux
              - os: macos-latest
                generator: Ninja
                cmake_args: ""
                artifact: nba-libretro_macOS
              - os: windows-latest
                generator: VS16Win64
                cmake_args: "-T clangcl"
                artifact: nba-libretro_windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run-cmake
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          cmakeGenerator: ${{ matrix.config.generator }}
          cmakeAppendedArgs: "-DCMAKE_BUILD_TYPE=Release ${{ matrix.config.cmake_args }}"
          buildDirectory: "${{ github.workspace }}/cmake-build"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: "${{ matrix.config.artifact }}"
          path: |
            ${{ github.workspace }}/cmake-build/nba_libretro.dll
            ${{ github.workspace }}/cmake-build/nba_libretro.so
            ${{ github.workspace }}/cmake-build/nba_libretro.dylib
